# directories
pagesdir:       input-pages
outputsdir:     output

# theme location
themefile:      themes/crown/theme.yaml

# metadata that shows up in the header and in metadata
title:          I'm afraid I can't do that
author:         HAL 9000
description:    The Blog of HAL 9000

# other settings
recentposts:    5

