# directories
pagesdir:       input-pages
outputsdir:     output

# theme location
themefile:      ../SampleThemes/crown/theme.yaml

# metadata that shows up in the header and in metadata
title:          I'm afraid I can't do that
author:         HAL 9000
description:    The Blog of HAL 9000

# other settings
recentposts:    5

# if you want to use google analytics, uncomment the line below and
# replace UA-1234-1 with your real UA tracking ID.
# don't forget to disable any ad blocker before testing! :)
# gtag:           UA-1234-1
